export const N1496492 = {
  ieltsInfo: null,
  pteInfo: {
    "70": "",
    firstTimeTestTaker: "Yes",
    testCentreId: "00011",
    gender: "Female",
    writtenDiscourse: "63",
    oralFluency: "67",
    countryOfResidence: "United Kingdom",
    reportIssueDate: "15 Feb 2019",
    testTakerId: "PTE987654321",
    speaking: "65",
    grammar: "",
    vocabulary: "59",
    scoreReportCode: "876543A21B",
    writing: "63",
    listening: "55",
    pronunciation: "45",
    spelling: "70",
    writing63: "",
    reading: "62",
    dateOfBirth: "12 Aug 1995",
    testCentreCountry: "United Kingdom",
    writtenDiscourse63: "",
    vocabulary59: "",
    pronunciation45: "",
    countryOfCitizenship: "China",
    oralFluency67: "",
    validUntil: "11 Feb 2021",
    regId: "987654321",
    testDate: "11 Feb 2019",
    spelling70: "",
  },
  studentPersonalInfo: {
    passportNo: "N 1496492",
    placeOfIssue: "THANE",
    placeOfBirth: "AMBERNATH, THANE, MAHARASHTRA",
    countryCode: "IND",
    surname: "MUSSA",
    sex: "M",
    name: "AZIM MUSSA",
    dateOfBirth: "01/08/1990",
    dateOfIssue: "23/07/2015",
  },
  englishProficiencyTestsType: "pte",
  studentId: "N 1496492",
  updatedAt: 1723348982125,
  createdAt: 1723348661399,
  studentBoardType: "RAJASTHAN",
  agentId: null,
  studentMarksheetInfo: [
    {
      totalMarks: 100,
      marksObtained: 81,
      subject: "HINDI(COMP)",
    },
    {
      totalMarks: 100,
      marksObtained: 83,
      subject: "ENGLISH(COMP)",
    },
    {
      totalMarks: 100,
      marksObtained: 82,
      subject: "PHYSICS",
    },
    {
      totalMarks: 100,
      marksObtained: 80,
      subject: "CHEMISTRY",
    },
    {
      totalMarks: 100,
      marksObtained: 91,
      subject: "BIOLOGY",
    },
  ],
};
