export const U4600381 = {
  ieltsInfo: {
    date: "",
    listening: "6.0",
    note: "",
    schemeCode: "Private Candidate",
    b: "6.0",
    testReportForm: "ACADEMIC",
    administratorSSignature: "18/07/2023",
    countryOrRegionOfOrigin: "",
    cefrLevel: "B2",
    cidateNumber: "193794",
    reading: "5.0",
    dateOfBirth: "13/03/2005",
    centreStamp: "idp IELTS TEST CENTRES /N855",
    testReportFormNumber: "23IN193794SACS855A",
    validationStamp: "IELTS",
    firstName: "SRISHTI",
    centreNumber: "IN855",
    speaking: "6.0",
    familyName: "SACHDEVA",
    writing: "6.0",
    cidateId: "U2955985",
    sexMf: "F",
    administratorComments: "",
    firstLanguage: "HINDI",
  },
  pteInfo: null,
  studentPersonalInfo: {
    passportNo: "U4600381",
    placeOfIssue: "DELHI",
    placeOfBirth: "NEW DELHI, DELHI",
    countryCode: "IND",
    surname: "ARYAN",
    sex: "M",
    name: "ARYAN",
    dateOfBirth: "17/06/2003",
    dateOfIssue: "05/03/2020",
  },
  englishProficiencyTestsType: "ielts",
  studentId: "U4600381",
  updatedAt: 1723707834325,
  createdAt: 1723707786707,
  studentBoardType: "PUNJAB",
  agentId: null,
  studentMarksheetInfo: [
    {
      totalMarks: 100,
      marksObtained: 77,
      subject: "GENERAL ENGLISH",
    },
    {
      totalMarks: 100,
      marksObtained: 83,
      subject: "GENERAL PUNJABI",
    },
    {
      totalMarks: 100,
      marksObtained: 73,
      subject: "PHYSICS",
    },
    {
      totalMarks: 100,
      marksObtained: 79,
      subject: "CHEMISTRY",
    },
    {
      totalMarks: 100,
      marksObtained: 83,
      subject: "BIOLOGY",
    },
    {
      totalMarks: 50,
      marksObtained: 40,
      subject: "ENVIRONMENTAL EDUCATION",
    },
    {
      totalMarks: 100,
      marksObtained: 90,
      subject: "COMPUTER SCIENCE",
    },
    {
      totalMarks: 100,
      marksObtained: 89,
      subject: "WELCOME LIFE",
    },
  ],
};
